### ISSUE TITLE
contrib-assessment not working with framework v2.2.2

### ISSUE THREAD

**Issue by canstudios-nicolaw** [adaptlearning/adapt_framework#1832]
Assessment & Framework versions used:
Assessment extension v2.1.2 
Framework v2.2.2

Previewing a course that contains an assessment extension since upgrading the framework gives the following error in the console:
```
ERROR: Error during app:dataLoading trigger TypeError: this.findDescendantModels is not a function
Uncaught TypeError: Cannot read property 'length' of null
    at n._removeQuestionListeners (adapt.min.js:9)
    at n._onRemove (adapt.min.js:10)
    at _ (backbone.js:2)
    at m (backbone.js:2)
    at f (backbone.js:2)
    at n.u.trigger (backbone.js:2)
    at n.i.remove (adapt.min.js:1)
    at n.removeViews (adapt.min.js:2)
    at n.handleCourse (adapt.min.js:2)
    at n.handleRoute (adapt.min.js:2)
_removeQuestionListeners @ adapt.min.js:9
_onRemove @ adapt.min.js:10
```

The error is coming from `_removeQuestionListeners (adapt-assessmentArticleModel.js:281)`

Steps to reproduce:
-Make new course
-Add assessment extension
-On article enable the extension and give it a name "a1"
-Add one mcq (I've given it a couple of answers and some feedback)
-Add assessment results component (I've given it some feedback text and a feedback band)
-Preview the course - I see the error - it just gets stuck on the loading spinner

**Comment by moloko** [comment]
does it still happen if you have more than one question?

**Comment by canstudios-nicolaw** [comment]
Yes it does. Oliver mentioned seeing it when quickly navigating to and from an assessment page, but I can't get as far as the page loading so I think this is a different issue

**Comment by tomgreenfield** [comment]
I'm afraid I cannot replicate this following the steps mentioned.

![image](https://user-images.githubusercontent.com/922987/31172393-4cc11522-a8fb-11e7-84b0-cf2b0b59dbda.png)

**Comment by canstudios-nicolaw** [comment]
I am sorry for wasting everyone's time. This has turned out to be an internal issue.

**Comment by oliverfoster** [comment]
out of interest, what was it?

**Comment by canstudios-nicolaw** [comment]
When we merged the latest framework into our project it didn't all get merged in! The findDescendantModels function was one of the things that was missing...

**Comment by moloko** [comment]
Looks like I win this one then ;-)

![2017-10-05 12_44_45-adaptlearning_adapt_framework - gitter](https://user-images.githubusercontent.com/1249597/31225664-02d89932-a9cb-11e7-8f20-9da924534fa4.png)

Then again I'm not one to talk, I disgraced myself yesterday by updating the wrong project with all the changes from #1779 then wasted much of mine and @oliverfoster 's time trying to figure out why it wasn't working in the project I should have applied it to :-(
